In [1]:
import torch
import torch.optim as optim
torch.__version__

'2.3.0+cu121'

입력데이터(X)와 출력데이터(Y) 정의

In [2]:
x_data = [[1],[2],[3],[4],[5],[6]]
y_data = [[0],[0],[0],[1],[1],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

초기 파라미터(W와 b) 설정

In [3]:
W = torch.zeros((1, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)


시그모이드 함수를 사용한 논리회귀모델의 가설

In [4]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))

비용함수(오차) 계산

In [5]:
losses = -(y_train * torch.log(hypothesis) +
           (1 - y_train) * torch.log(1 - hypothesis))
cost = losses.mean()

경사하강 알고리즘 설정

In [6]:
optimizer = optim.SGD([W, b], lr=1)

경사하강 알고리즘을 반복해서 동작
반복한 횟수별 Cost값(오차) 출력

In [7]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
    losses = -(y_train * torch.log(hypothesis) +
           (1 - y_train) * torch.log(1 - hypothesis))
    cost = losses.mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.148120
Epoch  200/1000 Cost: 0.105678
Epoch  300/1000 Cost: 0.085484
Epoch  400/1000 Cost: 0.072797
Epoch  500/1000 Cost: 0.063796
Epoch  600/1000 Cost: 0.056961
Epoch  700/1000 Cost: 0.051541
Epoch  800/1000 Cost: 0.047111
Epoch  900/1000 Cost: 0.043408
Epoch 1000/1000 Cost: 0.040259


학습한 모델에 대해서 Test하기

In [8]:
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print("---Hypothesis(논리회귀모델 결과값)---") ##논리회귀모델 결과값
print(hypothesis)

# 만약 가설 결과값이 0.5보다 크다면, 예측값을 1로 설정
# 그렇지않다면, 예측값을 0으로 설정
torch_tensor = hypothesis >= torch.FloatTensor([0.5])
prediction = torch_tensor.float()
print("---Prediction(예측값)---") ## 예측값
print(prediction) ## 예측값
print("---Ground truth(정답)---") ## 정답
print(y_train) ## 정답

correct_prediction = prediction.float() == y_train  ## 예측값과 정답과 비교

accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the training set.'.format(accuracy * 100))

---Hypothesis(논리회귀모델 결과값)---
tensor([[3.5196e-05],
        [2.2582e-03],
        [1.2705e-01],
        [9.0347e-01],
        [9.9834e-01],
        [9.9997e-01]], grad_fn=<MulBackward0>)
---Prediction(예측값)---
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
---Ground truth(정답)---
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
The model has an accuracy of 100.00% for the training set.
